###############################
# MNIST k8s DeepSpeed Example #
###############################
apiVersion: batch/v1
kind: Job
metadata:
  name: mnist
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/zihaozhou/nautilus_tutorial:torch113_cuda117_ds076
        command: ["/bin/bash","-c"]
        # NCCL_DEBUG=INFO
        args: ['git clone https://github.com/Rose-STL-Lab/nautilus_tutorial.git;
                cd nautilus_tutorial;
                deepspeed mnist_ds.py --deepspeed --deepspeed_config config.json --epochs 10']
        volumeMounts:
        - mountPath: /stpp-vol
          name: stpp-vol
        - mountPath: /dev/shm
          name: dev-shm
        resources:
          limits:
            nvidia.com/gpu: "4"
            memory: "20G"
            cpu: "12"
          requests:
            nvidia.com/gpu: "4"
            memory: "8G"
            cpu: "4"
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
      volumes:
        - name: stpp-vol
          persistentVolumeClaim:
            claimName: stpp-vol
        - name: dev-shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
